apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
    name: cluster 
spec:
  podResourceOverride:
    spec:
      memoryRequestToLimitPercent: 5 
      cpuRequestToLimitPercent: 5 
      limitCPUToMemoryPercent: 200 