# Certificate for external communication from clients outside the cluster
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-external-tls
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
      cert-utils-operator.redhat-cop.io/generate-java-keystores: "true"
  secretName: mq-external-tls-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: "extcert"
  subject:
    organizations:
      - 'mqss'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - '*.cp4i.svc'
    - '*.cp4i.svc.local'
    - '*.cp4i.svc.local.cluster'
    - '*.itzroks-50f1njf3h5-7hmmnn-1615bdf0ff9ba5518cb8d7760c84e878-0000.eu-de.containers.appdomain.cloud'
  issuerRef:
    name: mq-selfsigned-issuer
