apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:

  generation: 1
  labels:
    operators.coreos.com/datapower-operator.cp4i: ''
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:operators.coreos.com/datapower-operator.cp4i': {}
      manager: Go-http-client
      operation: Update
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:channel': {}
          'f:installPlanApproval': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
          'f:startingCSV': {}
      manager: Mozilla
      operation: Update
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
      subresource: status
  name: datapower-operator
  namespace: cp4i
spec:
  channel: v1.12
  installPlanApproval: Automatic
  name: datapower-operator
  source: ibm-datapower-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: datapower-operator.v1.12.2
