apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"datapower-operator"},"name":"ibm-datapower","namespace":"cp4i"},"spec":{"channel":"v1.11-sc2","name":"datapower-operator","source":"ibm-operator-catalog","sourceNamespace":"openshift-marketplace"}}
  resourceVersion: '9568529'
  name: ibm-datapower
  generation: 1
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:operators.coreos.com/datapower-operator.cp4i': {}
      manager: Go-http-client
      operation: Update
      
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          .: {}
          'f:channel': {}
          'f:name': {}
          'f:source': {}
          'f:sourceNamespace': {}
      manager: argocd-controller
      operation: Update
      
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:installedCSV': {}
          'f:currentCSV': {}
          'f:catalogHealth': {}
          'f:installPlanRef':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:namespace': {}
            'f:resourceVersion': {}
            'f:uid': {}
          'f:installPlanGeneration': {}
          'f:conditions': {}
          .: {}
          'f:installplan':
            .: {}
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
            'f:uuid': {}
          'f:lastUpdated': {}
          'f:state': {}
      manager: catalog
      operation: Update
  namespace: cp4i
  labels:
    app.kubernetes.io/instance: datapower-operator
    operators.coreos.com/datapower-operator.cp4i: ''
spec:
  channel: v1.11-sc2
  name: datapower-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
