kind: DataPowerService
apiVersion: datapower.ibm.com/v1beta3
metadata:
  name: quickstart
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-EYGU-PVGRBC
    use: nonproduction
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: datapower-admin
  version: 10.6-lts