apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: datapower
spec:
  version: 10.5-cd
  license:
    accept: true
    use: developers-limited
    license: L-PYDN-Q4NGNT
  replicas: 3
  users:
  - name: admin
    passwordSecret: datapower-admin
    accessLevel: privileged