kind: DataPowerService
apiVersion: datapower.ibm.com/v1beta3
metadata:
  name: quickstart
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-EYGU-PVGRBC
    use: nonproduction
  env:
  - name: DATAPOWER_INTERACTIVE
    value: "true"
  domains:
  - name: "default"
    dpApp:
      config:
        — web-config
      
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: '4Gi'
    requests:
      cpu: '1'
      memory: '2Gi'
  users:
    - name: admin
      accessLevel: privileged
      passwordSecret: dpadmin-credentials

  version: 10.6-lts