kind: DataPowerService
apiVersion: datapower.ibm.com/v1beta3
metadata:
  labels:
    backup.datapower.ibm.com/component: datapowerservice
  name: quickstart_2
  namespace: cp4i
spec:
  version: 10.5-cd
  license:
    accept: true
    use: developers-limited
    license: L-PYDN-Q4NGNT
  replicas: 3
  users:
  - name: admin
    passwordSecret: datapower-admin
    accessLevel: privileged