apiVersion: v1
kind: Service
metadata:
  name: db-webui
  namespace: cp4i
spec:
  selector:
    app.kubernetes.io/name: quickstart

  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090