kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: eventendpointmgr-ibm-eem-user-roles
stringData:
  user-mapping.json: >-
    {
    "mappings": [
        {
            "id": "eem-admin",
            "roles": [
                "author"
            ]
        },
        {
            "id": "es-user",
            "roles": [
                "viewer"
            ]
        }
    ]
    }
type: Opaque