kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: eventendpointmgr-ibm-eem-user-credentials
stringData:
  user-credentials.json: >-
    {
      "users": [
          {
              "username": "eem-admin",
              "password": "Th1$ISTh3Adm1nPa$SW0Rd"
          },
          {
              "username": "es-user",
              "password": "MyU$erPaS$WorD"
          }
      ]
    }
type: Opaque