kind: ConfigMap
apiVersion: v1
metadata:
  name: webgui
  namespace: cp4i
labels:
    app.kubernetes.io/component: datapower
    app.kubernetes.io/instance: cp4i-quickstart
    app.kubernetes.io/managed-by: datapower-operator
    app.kubernetes.io/name: datapower
    app.kubernetes.io/part-of: ibm-datapower-quickstart
  
data:
  web.cfg: |
    web-mgmt 
        admin-state "enabled"
        save-config-overwrite
        idle-timeout 600
        ssl-config-type server
        no disable-csrf
        enable-sts
    exit