kind: ConfigMap
apiVersion: v1
metadata:
  name: webgui
  namespace: cp4i
  
data:
  web.cfg: |
    web-mgmt 
        admin-state "enabled"
        save-config-overwrite
        idle-timeout 600
        ssl-config-type server
        no disable-csrf
        enable-sts
    exit