apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate these config maps from mqsc files to support
# syntax hignlighting in tooling.
configMapGenerator:
  - name: singleinstance-qm-configmap
    files:
      - qm-config/tls.mqsc
      - qm-config/mq.ini

generatorOptions:
  disableNameSuffixHash: true

resources: 
  # Resources for QM using a self signed cerver certificate.

  - qm.yaml
  - qm2.yaml
