apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: singleinstance-qm-2
  annotations:
    certmanager.k8s.io/disable-auto-restart: "true"
    configmap.reloader.stakater.com/reload: "singleinstance-qm-configmap"
    secret.reloader.stakater.com/reload: "mq-external-tls-secret"
spec:
  #telemetry:
  #  tracing:
  #    instana:
  #      enabled: true
  license:
    accept: true
    license: PATCHED_BY_KUSTOMIZE
    use: PATCHED_BY_KUSTOMIZE
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
            - name: APIX_LOGFILE
              value: stdout
            - name: LOG_LEVEL
              value: info
            - name: MONITOR_LEVEL
              value: debug
            - name: SPAN_FORMAT
              value: otel
            #- name: OTLP_EXPORTER_GRPC_ENDPOINT
            #  value: tempo-tempostack-distributor.openshift-tempo-operator.svc.cluster.local:4317
            - name: OTLP_EXPORTER_HTTP_URL
              value: tempo-tempostack-distributor.openshift-tempo-operator.svc.cluster.local:4318:/v1/traces
          name: qmgr
          image: image-registry.openshift-image-registry.svc:5000/cp4i/mq-otel
          imagePullPolicy: Always
  queueManager:
    mqsc:
      - configMap:
          name: singleinstance-qm-configmap
          items:
            - tls.mqsc
    ini: 
      - configMap:    
          name: singleinstance-qm-configmap
          items:
            - mq.ini
            - mq-exit.ini
    availability:
      type: SingleInstance
    name: SINGLEINSTANCEQM2
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      defaultClass: PATCHED_BY_KUSTOMIZE
      queueManager:
        type: persistent-claim
  version: 9.4.0.5-r2
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.crt
            - ca.crt
  web:
    enabled: true
